### ISSUE TITLE
Choices bug

### ISSUE THREAD

**Issue by ririko5834** [Androz2091/slash-commands-gui#9] opened 2021-04-19 10:13 UTC
Can't add choices just to one parameter, when I choose parameter and want to add choices, it will add them to every parameter.

**Comment by Androz2091** [comment] 2021-04-20 06:29
Hello, I can confirm this bug. It's pretty weird, I will try to fix it as soon as possible.

**Comment by ririko5834** [comment] 2021-04-20 06:35
Btw is it possible to set parameters for subcommands?

**Comment by Androz2091** [comment] 2021-04-20 06:53
Yes

**Comment by ririko5834** [comment] 2021-04-20 09:05
So that's another bug, if you set parameters to main command, you can't make subcommands

**Comment by ririko5834** [comment] 2021-04-20 09:07
Btw I have idea for your new project: Make serverless webhook sender (with embed creator gui)

**Comment by ririko5834** [comment] 2021-04-23 08:18
@Androz2091 When you will fix it?

**Comment by danshilm** [comment] 2021-05-21 18:29
> 
> 
> So that's another bug, if you set parameters to main command, you can't make subcommands

Not a bug. This is how it works on Discord's side.

**Comment by danshilm** [comment] 2021-05-21 18:30
> 
> 
> Btw I have idea for your new project: Make serverless webhook sender (with embed creator gui)

Multiple websites exist that do this already.

**Comment by ririko5834** [comment] 2021-05-22 13:06
> Multiple websites exist that do this already.

Send me some of them that can be selfhosted

**Comment by danshilm** [comment] 2021-05-22 13:29
> > Multiple websites exist that do this already.
> 
> Send me some of them that can be selfhosted

Why would you want to self host this? There's no data being stored, so I'm unsure what the merit of self hosting such an application would be.

**Comment by Androz2091** [comment] 2021-07-23 04:59
This is now fixed!

**Closed by Androz2091** 2021-07-23 04:59 UTC
Labels: bug
